version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  web:
    build: .
    command: sh -c "sleep 10 && python /cctv-app/Website/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/cctv-app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL} 
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
