# Generated by Django 5.0.3 on 2025-01-14 00:55

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera_Settings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cam_name", models.CharField(max_length=200)),
                ("feed_src", models.CharField(max_length=200)),
                ("x1", models.IntegerField(default=0)),
                ("y1", models.IntegerField(default=0)),
                ("x2", models.IntegerField(default=0)),
                ("y2", models.IntegerField(default=0)),
                ("x3", models.IntegerField(default=0)),
                ("y3", models.IntegerField(default=0)),
                ("x4", models.IntegerField(default=0)),
                ("y4", models.IntegerField(default=0)),
                ("x5", models.IntegerField(default=0)),
                ("y5", models.IntegerField(default=0)),
                ("x6", models.IntegerField(default=0)),
                ("y6", models.IntegerField(default=0)),
                ("x7", models.IntegerField(default=0)),
                ("y7", models.IntegerField(default=0)),
                ("x8", models.IntegerField(default=0)),
                ("y8", models.IntegerField(default=0)),
                ("cam_is_active", models.BooleanField(default=False)),
                ("gender_detection", models.BooleanField(default=False)),
                ("face_detection", models.BooleanField(default=False)),
                ("face_capture", models.BooleanField(default=False)),
                ("id_card_detection", models.BooleanField(default=False)),
                ("uniform_detection", models.BooleanField(default=False)),
                ("shoes_detection", models.BooleanField(default=False)),
                ("ciggerate_detection", models.BooleanField(default=False)),
                ("sit_detection", models.BooleanField(default=False)),
                (
                    "cam_start",
                    models.CharField(
                        blank=True, default="00:01", max_length=200, null=True
                    ),
                ),
                (
                    "cam_stop",
                    models.CharField(
                        blank=True, default="23:59", max_length=200, null=True
                    ),
                ),
                (
                    "attendance_time_start",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "attendance_time_end",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "leaving_time_start",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "leaving_time_end",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "role_camera",
                    models.CharField(
                        choices=[
                            ("P_IN", "Presence_In"),
                            ("P_OUT", "Presence_Out"),
                            ("T", "Tracking"),
                        ],
                        default="T",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coorporates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Counted_Instances",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=200)),
                ("male_entries", models.IntegerField(default=0)),
                ("female_entries", models.IntegerField(default=0)),
                ("unknown_gender_entries", models.IntegerField(default=0)),
                ("staff_entries", models.IntegerField(default=0)),
                ("intern_entries", models.IntegerField(default=0)),
                ("unknown_role_entries", models.IntegerField(default=0)),
                ("people_exits", models.IntegerField(default=0)),
                ("people_inside", models.IntegerField(default=0)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.camera_settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Divisions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                (
                    "corporate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.coorporates",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personnels",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[("S", "Staff"), ("I", "Intern")], max_length=100
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                (
                    "division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.divisions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personnel_Images",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_path", models.CharField(max_length=255, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Dashboard.personnels",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personnel_Entries",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                (
                    "presence_status",
                    models.CharField(
                        choices=[
                            ("ONTIME", "On Time"),
                            ("LATE", "Late"),
                            ("LEAVE", "Already Leave"),
                            ("UNKNOWN", "No Presence"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("image", models.CharField(max_length=255, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.camera_settings",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.personnels",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work_Timer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("SIT", "Sit"), ("FACE_DETECTED", "Face Detected")],
                        max_length=15,
                    ),
                ),
                ("timer", models.IntegerField(default=0)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.camera_settings",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.personnels",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("corporate_admin", "Corporate Admin"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("is_superadmin", models.BooleanField(default=False)),
                ("is_cooperate_admin", models.BooleanField(default=False)),
                ("is_employee", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdmins",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="personnels",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coorporates",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
