# Generated by Django 5.0.3 on 2024-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera_settings",
            name="attendance_time_end",
            field=models.CharField(default="00:00:00", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camera_settings",
            name="attendance_time_start",
            field=models.CharField(default="00:00:00", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camera_settings",
            name="leaving_time_start",
            field=models.CharField(default="00:00:00", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personnel_entries",
            name="time_in",
            field=models.CharField(default="00:00:00", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personnel_entries",
            name="time_out",
            field=models.CharField(default="00:00:00", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personnels",
            name="employment_status",
            field=models.CharField(
                choices=[("S", "Staff"), ("I", "Intern"), ("U", "Unknown")],
                default="U",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
