# Generated by Django 5.0.3 on 2025-01-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnels",
            name="coorporate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashboard.coorporates",
            ),
        ),
        migrations.DeleteModel(
            name="SuperAdmins",
        ),
    ]
