# Generated by Django 5.0.3 on 2024-09-25 01:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0002_camera_settings_attendance_time_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnel_entries",
            name="name",
        ),
        migrations.RemoveField(
            model_name="personnel_entries",
            name="time_in",
        ),
        migrations.RemoveField(
            model_name="personnel_entries",
            name="time_out",
        ),
        migrations.AddField(
            model_name="camera_settings",
            name="leaving_time_end",
            field=models.CharField(
                default=datetime.time(1, 24, 9, 367107), max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personnel_entries",
            name="personnel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashboard.personnels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personnel_entries",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONTIME", "On Time"),
                    ("LATE", "Late"),
                    ("LEAVE", "Already Leave"),
                ],
                default="late",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personnels",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="Personnel_Images",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="personnel_pics/%Y/%m/%d/")),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Dashboard.personnels",
                    ),
                ),
            ],
        ),
    ]
