# Generated by Django 5.0.3 on 2025-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0002_personnels_coorporate_delete_superadmins"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coorporates",
            new_name="Company",
        ),
        migrations.RenameField(
            model_name="customusers",
            old_name="is_cooperate_admin",
            new_name="is_admin",
        ),
        migrations.RenameField(
            model_name="divisions",
            old_name="corporate",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="personnels",
            old_name="coorporate",
            new_name="company",
        ),
        migrations.AlterField(
            model_name="customusers",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("employee", "Employee"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
