# Generated by Django 5.0.3 on 2024-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0003_remove_personnel_entries_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel_images",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
