# Generated by Django 5.0.3 on 2024-09-25 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_personnel_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel_images',
            old_name='image',
            new_name='image_path',
        ),
        migrations.RemoveField(
            model_name='personnel_entries',
            name='status',
        ),
        migrations.AddField(
            model_name='personnel_entries',
            name='presence_status',
            field=models.CharField(choices=[('ONTIME', 'On Time'), ('LATE', 'Late'), ('LEAVE', 'Already Leave')], default='LATE', max_length=10),
        ),
        migrations.AddField(
            model_name='personnel_images',
            name='predicted_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personnel_images',
            name='personnel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Dashboard.personnels'),
        ),
    ]
