# Generated by Django 5.0.3 on 2025-01-15 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0004_alter_customusers_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
        migrations.AddField(
            model_name="camera_settings",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashboard.company",
            ),
        ),
        migrations.AddField(
            model_name="customusers",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Dashboard.company",
            ),
        ),
    ]
