# Generated by Django 5.0.3 on 2024-09-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_rename_image_personnel_images_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counted_instances',
            name='intern_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counted_instances',
            name='staff_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counted_instances',
            name='unknown_role_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='employment_status',
            field=models.CharField(choices=[('S', 'Staff'), ('I', 'Intern')], max_length=100),
        ),
    ]
