# Generated by Django 5.0.3 on 2024-10-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_counted_instances_intern_entries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel_entries',
            name='presence_status',
            field=models.CharField(choices=[('ONTIME', 'On Time'), ('LATE', 'Late'), ('LEAVE', 'Already Leave'), ('UNKNOWN', 'No Presence')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='personnel_entries',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
