# Generated by Django 5.0.3 on 2024-10-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_personnel_images_predicted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel_entries',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
