# Generated by Django 5.0.3 on 2025-01-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0009_rename_epmloyee_id_personnels_employee_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personnels",
            old_name="employee_id",
            new_name="employeeid",
        ),
    ]
