# Generated by Django 5.0.3 on 2024-12-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_personnel_entries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_settings',
            name='extract_capture',
            field=models.BooleanField(default=False),
        ),
    ]
