# Generated by Django 5.0.3 on 2025-01-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0010_rename_employee_id_personnels_employeeid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnels",
            name="employeeid",
        ),
    ]
