# Generated by Django 5.0.3 on 2024-12-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_camera_settings_extract_capture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera_settings',
            old_name='extract_capture',
            new_name='face_capture',
        ),
    ]
