# Generated by Django 5.0.3 on 2025-01-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0011_remove_personnels_employeeid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnels",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="personnels",
            name="gender",
        ),
    ]
