# Generated by Django 5.0.3 on 2025-02-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0012_remove_personnels_employment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusers",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
